// <auto-generated />
namespace UAHFitVault.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class devadmintoolsbranchmerge : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(devadmintoolsbranchmerge));
        
        string IMigrationMetadata.Id
        {
            get { return "201601312058190_dev-admintools-branchmerge"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
