// <auto-generated />
namespace UAHFitVault.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class devadmintoolbranchmerge : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(devadmintoolbranchmerge));
        
        string IMigrationMetadata.Id
        {
            get { return "201601311633136_dev-admintoolbranch-merge"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
