// <auto-generated />
namespace UAHFitVault.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class id_change_12816 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(id_change_12816));
        
        string IMigrationMetadata.Id
        {
            get { return "201601290403106_id_change_1-28-16"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
