// <auto-generated />
namespace UAHFitVault.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class basissummarforeignkey2_12916 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(basissummarforeignkey2_12916));
        
        string IMigrationMetadata.Id
        {
            get { return "201601300321551_basissummar-foreignkey2_1-29-16"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
